### PR TITLE
Add OAuth 2.0 support

### PR DESCRIPTION
**Pull request by famzah**
This commit adds OAuth 2.0 support, which currently is the only method for a script to authenticate to the Google platform. The "sample_util.py" is used (imported) by the following samples:
- blogger/BloggerExample.py
- sites/sites_example.py
- docs/docs_v3_example.py
- analytics/account_feed_demo.py
- analytics/mgmt_feed_demo.py
- analytics/data_feed_demo.py
- apps/marketplace_sample -- there is a copy of "sample_util.py" in the "gdata/" subfolder

I've verified the change by testing with "samples/sites/sites_example.py".

### CODE REVIEW

**Comment by famzah** [comment]
I signed the CLA.

**Comment by famzah** [comment]
Anyone? :)

**Comment by gilcreque** [comment]
+1

**Comment by aliafshar** [comment]
Thanks.

**Pull request merged**
