### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by mitya57**
* `emailsettings_pop_settings.py`: Fix syntax error
* `gdata/service.py`: Handle HTTP 301 redirects in addition to HTTP 302 ones (see [googlecode #693](https://code.google.com/p/gdata-python-client/issues/detail?id=693)).
* `tests/module_test_runner.py`: Make tests return non-zero status on failures, and increase verbosity.

### CODE REVIEW

**Comment by mitya57** [comment]
I have just signed the CLA.

**Comment by aliafshar** [comment]
Thanks. :+1:

**Comment by aliafshar** [comment]
p.s. what APIs do you use this library with?

**Comment by mitya57** [comment]
I used to use it for Google Docs/Drive, now I do not use it (mostly because Python 3 is not supported), but I am still maintaining the [package in Debian](https://tracker.debian.org/pkg/python-gdata).

**Pull request merged**
